### ISSUE TITLE
Add helper functions for GCP firewall resource

### ISSUE THREAD

**Issue by sukchomb-zz** [GoogleCloudPlatform/inspec-gcp-helpers#10]
Hi @binamov , @KonradSchieban, 

Many thanks for your time on today’s call.

Within the engineering team, we have 4  GCP Inspec (currently using version 4.18.100) based guardrails that help ensure that the platform remains compliant with respect to the usage of firewalls.

Each guardrail ensures various properties of each firewall are aligned to a specific control definition.
 
During execution, the guardrails make a call to the plural resource 
`google_compute_firewalls(project: gcp_project_id).firewall_names.each do |firewall_name|`

and for each firewall name returned the singular resource is invoked thus

`fw = google_compute_firewall(project: gcp_project_id, name: firewall_name)`

it then goes on to process the various attributes in each firewall accordingly.

These are new guardrails delivered into the deployment environment just recently.

During the deployment pipeline execution phase, the 4 guardrails are executed to ensure that any changes performed by the Terraform modules remain compliant.

The pipeline fails against any non-compliance.

Firewalls exist in only specific GCP projects and it is the pipeline execution time that has now grown massively for these projects.

Having a cache of all the firewalls available before the start on the guard rail would permit iterating over them reducing the execution time of pipeline job.

Each guardrail makes use of properties exposed by `google_compute_firewall(project: gcp_project_id, name: firewall_name)` .

However one guardrail goes further and makes use of this particular method for each port listed.

` fw.single_port_matches('1-19', this_port) `

identified here `https://github.com/inspec/inspec-gcp/blob/f7b2ac38e68b46e747eaede10e7f14e12b800df6/libraries/google_compute_firewall.rb#L234`

Please let me know if any further information is required.

Thanks,

Sukhjit

**Comment by KonradSchieban** [comment]
Thank you @sukchomb for raising this feature request and the detailed explanation of what is needed! This is a valid use case and can probably used in other repositories as well. It should be straight-forward to implement this.

I will get back to you soon and provide an update.

**Comment by KonradSchieban** [comment]
@sukchomb can you please review the linked pull request and check if this implements your requirements?
