### ISSUE TITLE
Log/report all permission errors clearly

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/inspec-gcp-helpers#9]
Hi Team,

Would it be possible to log or report all permission errors clearly when running the benchmarks? Currently, when we run them on a project and it returns zero findings for a group of resources, it's hard to tell if this is because they are fully compliant, or if the benchmark SA simply didn't have access to them.

Please note that some permission errors to get reported, but only as cryptic stacktraces:
```json
{
  "status": "failed",
  "code_desc": "Control Source Code Error inspec-gcp-cis-benchmark/controls/1.01-iam.rb:25 ",
  "run_time": 0.000109905,
  "start_time": "2020-05-29T20:25:39+00:00",
  "message": "Bad response: #<Net::HTTPForbidden:0x000055e7894a85f0>",
  "exception": "RuntimeError",
  "backtrace": [
    "/var/lib/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/rule.rb:61:in `block (2 levels) in initialize'",
    "/var/lib/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'",
    "...",
    "/var/lib/gems/2.7.0/gems/inspec-bin-4.19.0/bin/inspec:11:in `<top (required)>'",
    "/usr/local/bin/inspec:23:in `load'",
    "/usr/local/bin/inspec:23:in `<main>'"
  ]
}
```

Others are not reported at all, and in fact are silently treated as "no resources found", resulting in false positives. For example, when we run the GKE benchmark and the SA doesn't have permission to list clusters, then it's reported as
```
[<project_id>] does not have any GKE clusters, this section of tests is Not Applicable.
```
even though the clusters are there. So in these cases the permission errors should be caught and reported as such, instead of being treated as absence of resources.

What we'd like to see ultimately is a clear error message for each control, which lists the missing permission(s), like so:
```
[<project_id>] <service_account_email> does not have <service.resource.action> permission to access <resource_uri>
```

Thanks!

Related issues that depend on its resolution:
https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/54
https://github.com/GoogleCloudPlatform/inspec-gke-cis-benchmark/issues/5

**Comment by KonradSchieban** [comment]
Agreed that any issue due to lacking permissions (or other reasons) should not be handled silently. Thanks for raising the issue!

**Comment by dinvlad** [comment]
Thanks - I've also noticed that Compute Engine benchmarks seem to report permission errors well. Perhaps other APIs could borrow their logic from those?

**Comment by KonradSchieban** [comment]
Yes, each cache object will have to be reviewed in a similar way (IAM, GCE, GKE, Cloud SQL, KMS, etc.). All cache classes inherit from the same base class, maybe they can share some common logic to catch the permission error.

**Comment by KonradSchieban** [comment]
Hi @dinvlad , I have been looking into how to address this issue and it seems like some inspec resources in inspec-gcp do not provide any kind of error message or code that can be used in the cache classes. In other words, inspec is unable to tell if the returned arrays to list resources should actually be empty or are empty because of lacking permissions.

I think this issue needs to be raised on https://github.com/inspec/inspec-gcp. Ideally any resource would provide a 4xx error or some kind of exception message if permissions are missing.

**Comment by dinvlad** [comment]
Yes, makes sense! Thanks.
